### ISSUE TITLE
day13 bug?

### ISSUE THREAD

**Issue by dcts** [erikw/advent-of-code-solutions#4]
reading day13 description, this condition should be true:
```js
inOrder([0,0,0], 2) === inOrder([0,0,0], [2])
```

But when I run your code with the above input, it shows different results:
```
inOrder([0,0,0], 2); // => false
inOrder([0,0,0], [2]); // => true
```

Is this a bug? (I know, odds are high that its not! But just in case...!)

This is an experpt from the puzzle description taken from https://adventofcode.com/2022/day/13
> If exactly one value is an integer, convert the integer to a list which contains that integer as its only value, then retry the comparison. For example, if comparing [0,0,0] and 2, convert the right value to [2] (a list containing 2); the result is then found by instead comparing [0,0,0] and [2].

**Comment by erikw** [comment]
Hey, I'm on my phone now so I can't check 
However I do think I remember that I checked my input and concluded that the most outer type was always Array in my input for the message pairs. Thus I more the shortcut assuming thst the input to `inOrder` will always be Arrays. 

Though sub-arrays are converted correctly in the recursive function:)

**Comment by erikw** [comment]
I think adding this at the top of the `cmp` function should fix it:

```javascript
export const cmp = (left, right) => {
  left = [left].flat();
  right = [right].flat();
   ...

```

**Comment by erikw** [comment]
Fixed by https://github.com/erikw/advent-of-code-solutions/commit/c5630b877f933991c5f836f86d38b5bb09c190a1

**Comment by dcts** [comment]
Cool yeah I saw it now, thanks for responding, helped me understand the solution! :)
